"""restructure_agents_add_source_emoji_openclaw

Revision ID: 72f398bbf35f
Revises: 073c3f313d95
Create Date: 2026-02-25 07:58:40.256286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f398bbf35f'
down_revision: Union[str, None] = '073c3f313d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new columns with server defaults so existing rows get values
    op.add_column('agents', sa.Column('source', sa.String(length=32), nullable=False, server_default='local'))
    op.add_column('agents', sa.Column('emoji', sa.String(length=16), nullable=False, server_default=''))
    op.add_column('agents', sa.Column('openclaw_workspace', sa.String(length=512), nullable=True))

    # Migrate existing head/sub role values → agent
    op.execute("UPDATE agents SET role = 'agent' WHERE role IN ('head', 'sub')")

    # Migrate workspace paths: userdata/head → userdata/agents/{id}, userdata/sub/{id} → userdata/agents/{id}
    op.execute("UPDATE agents SET workspace_path = 'userdata/agents/' || id WHERE workspace_path LIKE 'userdata/head%' OR workspace_path LIKE 'userdata/sub/%'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'openclaw_workspace')
    op.drop_column('agents', 'emoji')
    op.drop_column('agents', 'source')
    # ### end Alembic commands ###
